-- validation.lua

local tests = {
  book = "books",
  car = "cars",
  house = "houses",
  apple = "apples",
  cat = "cats",
  man = "men",
  woman = "women",
  child = "children",
  person = "people",
  tooth = "teeth",
  foot = "feet",
  mouse = "mice",
  louse = "lice",
  goose = "geese",
  ox = "oxen",
  sheep = "sheep",
  fish = "fish",
  deer = "deer",
  species = "species",
  series = "series",
  knife = "knives",
  life = "lives",
  elf = "elves",
  wolf = "wolves",
  calf = "calves",
  roof = "roofs",
  chef = "chefs",
  chief = "chiefs",
  belief = "beliefs",
  city = "cities",
  boy = "boys",
  day = "days",
  baby = "babies",
  potato = "potatoes",
  tomato = "tomatoes",
  hero = "heroes",
  box = "boxes",
  bus = "buses",
  dress = "dresses",
  church = "churches",
  brush = "brushes",
  quiz = "quizzes",
  photo = "photos",
  piano = "pianos",
  halo = "halos"
}

return tests
